### ISSUE TITLE
The Java version used to compile and run the Buildscript should be configurable

### ISSUE THREAD

**Issue by coderbot16** [CoolCrabs/brachyura#20]
In the case of Iris, we need to use a Java 11 library in our build script, but Brachyura assuming that it is Java 8 causes things to break by default for many people.

**Comment by Geolykt** [comment]
I can second it as being annoying to the point that I had to outsource the bulk of the buildscript to a seperate project

**Comment by CoolMineman** [comment]
closed by 10e2f2acee69e1b43f618360aa2d9824720cf8ca
