### ISSUE TITLE
Intellij/General IDE Enhancements

### ISSUE THREAD

**Issue by CoolMineman** [CoolCrabs/brachyura#3]
Allow generating both buildscript project and main project project together.
Allow auto updating classpath when buildscript changes maybe use https://plugins.jetbrains.com/plugin/7177-file-watchers or write a custom plugin?
Add source jars to intellij buildscripts

**Comment by IMS212** [comment]
when

**Comment by CoolMineman** [comment]
when the

**Comment by IMS212** [comment]
when the :flushed:
